name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install Pods
        working-directory: iosApp
        run: |
          pod install

      - name: Build
        working-directory: iosApp
        run: |
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            build

      - name: Test
        working-directory: iosApp
        run: |
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphonesimulator \
            test
