name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Kotlin shared module
        run: |
          ./gradlew :shared:build

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install Pods
        working-directory: iosApp
        run: |
          pod install

      - name: Build iOS App
        working-directory: iosApp
        run: |
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            build
